# Docker Compose file for testing
#
version: "2"
services:
  web_test:
    build:
      context: ..
      dockerfile: ./Dockerfile
    image: docker_web_test
    network_mode: bridge
    ports:
        - "127.0.0.1:3031:3031"
    volumes:
        - ./uwsgi-test.ini:/etc/uwsgi/uwsgi.ini
