# Docker Compose file for testing
version: "2"
services:

  web_test:
    build:
      context: ..
      dockerfile: ./Dockerfile
    network_mode: bridge
    command: py.test --junitxml=/data/test_report.xml --cov-report xml:/data/coverage.xml
